config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  resources :products, only: [:index, :new, :create] do

    namespace :admin do
      resources :products, only: [:new, :create, :show]
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: 'cart/items'
  resources :orders
  post '/additem', to: 'orders#add_item'

# get '/cart/checkout', to: 'orders#new', as: :checkout
# patch '/cart/checkout', to: 'orders#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items, class_name: 'OrderItem'
    belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  # attr_accessor :title, :description, :price, :image_filename
  validates :title, presence: true
end
  #mount_uploader :image_filename, Image_filenameUploader
#end

app/models/shopping_cart.rb
# class ShoppingCart < ApplicationRecord
#   has_one :order
#   has_many :items, through: :order, class_name: 'OrderItem'
#   belongs_to :user
#   delegate :subtotal, to: :order

#   attr_accessor :token

#     def initialize(token)
#       super ()
#       @token = token.to_s
#     end

#     def order
#       @order ||= Order.find_or_create_by(token: @token, status: 'cart', first_name: 'test', last_name: 'test') do |order|
#         order.update_attribute(:subtotal, 0)
#       end
#     end


#     def items_count
#       order.items.sum(:quantity)
#     end

#     def add_item(product_id, quantity=1)
#       product = Product.find(product_id)
#       order_item = order.items.find_or_create_by(price: product.price, quantity: quantity)
#       ActiveRecord::Base.transaction do
#         order_item.save
#         update_subtotal!
#       end
#     end


#     def remove_items(id:)
#       ActiveRecord::Base.transaction do
#         order.items.destroy(id)
#         update_subtotal!
#       end
#     end

#     private

#     def update_subtotal!
#       order.subtotal = order.items.sum('quantity * price')
#       order.save
#     end

# end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @products = Products.new
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
#   before_action :current_cart

#   def current_cart
#     @current_cart ||= ShoppingCart.new(token: cart_token)
#   end

#   helper_method :current_cart

#   private
# #how does api work into this?
#     def cart_token
#       return @cart_token unless @cart_token.nil?

#       session[:cart_token] ||= SecureRandom.hex(5)
#       @cart_token = session[:cart_token]
#     end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
    rescue_from Stripe::CardError, with: :catch_exception
    def new
    end
  
    def create
      StripeChargesServices.new(charges_params, current_user).call
      redirect_to new_charge_path
    end
  
    private
  
    def charges_params
      params.permit(:stripeEmail, :stripeToken, :order_id)
    end
  
    def catch_exception(exception)
      flash[:error] = exception.message
    end
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
    @items = current_user.orders.first.items
  end

  def create
  end

  def destroy
    current_item.destroy
    redirect_to cart_path
  end

  private

  helper_method :current_item
  def current_item
    OrderItem.find(params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
  end

  def create
  end

   def add_item
    product_id = params[:product_id]
    quantity = params[:quantity]
    product = Product.find(product_id)
    order_item = current_order.items.find_or_create_by(product: product, quantity: quantity, order_id: current_order.id)
    redirect_to cart_path
  end

  private


  helper_method :current_order
  def current_order
    current_user.orders.each do |order|
      if order.status == "cart"
        return @order = order
      end
    end
    if !@order
      return @order = current_user.orders.create(status: "cart")
    end
  end

  def order_params
    params.require(:order).permit(:user_id, :status, :subtotal)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.order(:title)
  end
   
  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add A Product</h1>
    <%= simple_form_for @product, url: ????_path do |f| %>
    <%= f.input :title %>
    <%= f.input :image_filename %>
    <%= f.input :description %>
    <%= f.input :price %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/charges/index.html.erb
<script src="https://js.stripe.com/v3/"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Satisfy&display=swap');
    @import url('https://fonts.googleapis.com/css?family=Montserrat&display=swap');
    </style>
  </head>

  <body>
   <div id="flex-content-container">
<!-- new navbar -->
    <div class="main-menu">
      <nav class="navbar navbar-toggleable-md navbar-dark bg-dark">
          <button class="navbar-toggler navbar-toggler-left" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
         <!--  <div class="collapse navbar-collapse" id="navbarTogglerDemo02"> -->
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item active">
                <a class="nav-link" <%= link_to "Products", root_path %> <span class="sr-only">(current)</span></a>
                <!-- additional products that can be added
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Stock Pins</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Clearance</a>
              </li> -->
                  <% if user_signed_in? %>
                    <li class="nav-item">
                      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                    </li>
                  <% else %>
                    <li class="nav-item">
                      <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                    </li>
                  <% end %>

              </ul>
              <ul class="navbar-nav ml-auto mt-2 mt-md-0">
                <i class= "fas fa-shopping-cart"> </i>
              </ul>
          </div>
      </nav>
    </div>

    <!-- alerts -->
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>


    <%= yield %>
 </div>
</br>
</br>



    <div id="footer">
      <div class="container">
        <b>Admin</b>
        <br />
        <%= link_to 'Add products', '#' %> </br>
      </div>
    </div>
  </body>
</html>

app/views/order_items/index.html.erb
</br>
<h2>Current Cart</h2>
</br>

<table>
  <thead>
    <tr>
    <!-- arrange these -->
      <td>Product</td>
      <td>Price</td>
      <!-- <td>Quantity</td> -->
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.product.title %></td>
      <td><%= number_to_currency item.product.price %></td>
      <!-- <td><%= item.quantity %></td> -->
      <td>
        <%= form_for item, method: :delete do |f| %>
          <%= f.submit "Remove" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>

    <tfoot>
    <tr>
      <td colspan="4" align="right">
      <td>
    </tr>
  </tfoot>
</table>

</br>
</br>
<div class="button1">
<button type="button" class="btn btn-success">
</div>

</br>
</br>

app/views/orders/new.html.erb
</br>
<h2> Checkout </h2>
</br>

<%= form_for @order, url: checkout_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

<div class="button3">
  <%= f.submit 'Continue to Purchase' %>
</div>
<% end %>

app/views/products/index.html.erb
<header>
  <div class="hero">
    <div class="frosty">
      <h1 class="title">Chestnut Feather</h1>
      </br>
      <h3>artistic and beaded leather designs for the equestrian</h3>
    </div>
    <div class="header col-6 offset-2">
    </div>
  </div>
</header>

</br>
</br>
</br>
</br>


<!--Product Cards   -->

<h2>
Products </h2>
</br>
</br>
<div class="container">
  <div class="row">
    <% @product.each do |product| %>
      <div class="col-sm">
        <div class="card" style="width: 18rem;">
          <% if product.image_filename%>
            <%= link_to image_tag (product.image_filename), product.image_filename %>
          <% end %>
            <!-- <img src="art_deco.png" class="card-img-top" alt="..."> -->
          <div class="card-body">
            <h5 class="card-title"><%= product.title %></h5>
            <p class="card-text"><%= product.description %></br> <%= number_to_currency product.price %></p>
            <%= form_tag additem_path do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%= number_field_tag :quantity, 1, size: 3 %>
              <%= submit_tag "Add to Cart", class: "button2" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>